# Generated by Django 4.0 on 2022-01-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=218)),
                ('desciption', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=28)),
                ('deadline', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
